/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Admin' at '3/27/17 4:33 PM' with Gradle 2.14.1
 *
 * @author Admin, @date 3/27/17 4:33 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
